### ISSUE TITLE
AWSLambdaFullAccess deprecated

### ISSUE THREAD

**Issue by pahud** [awslabs/aws-cloudfront-extensions#100]
The policy name `AWSLambdaFullAccess` is deprecated. We should use `AWSLambda_FullAccess ` instead.

https://github.com/awslabs/aws-cloudfront-extensions/blob/0ce548216c11fd3aba24efec2264758b4c858531/edge/nodejs/anti-hotlinking/template.yaml#L62

see https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Language (Version):**

**Comment by pahud** [comment]
Hi @NingLu  please check it out.

**Comment by NingLu** [comment]
Thanks, will fix it in next release

**Comment by NingLu** [comment]
The issue has been fixed, more details are at: https://github.com/awslabs/aws-cloudfront-extensions/commit/acf7b48052ff2c2cdca4f03150275f00455b409b
