### ISSUE TITLE
http302 function ARN get wrong value

### ISSUE THREAD

**Issue by RicoToothless** [awslabs/aws-cloudfront-extensions#102]
I can't get the http302 function ARN

https://github.com/awslabs/aws-cloudfront-extensions/blob/3dff29ed27b7851f729b846be4789eeded26dabf/edge/nodejs/http302-from-origin/template.yaml#L62

![image](https://user-images.githubusercontent.com/39393540/113404842-66fe6100-93db-11eb-8900-59ee5ba14210.png)

### Reproduction Steps

```
cd edge/nodejs/http302-from-origin
sam deploy --guided --capabilities CAPABILITY_NAMED_IAM
```

### What did you expect to happen?

get right http302 function ARN

### What actually happened?

I get `Http302Function` value

### Environment

  - **CDK CLI Version  : 1.21.1**
  - **Framework Version: **
  - **Language (Version): node v15.11.0** 

### Other

I can fix this.

**Comment by pahud** [comment]
@NingLu

**Comment by NingLu** [comment]
It's been fixed, close it
