### ISSUE TITLE
serving-based-on-device function timeout issue

### ISSUE THREAD

**Issue by RicoToothless** [awslabs/aws-cloudfront-extensions#112]
serving-based-on-device event type is [viewer request](https://github.com/awslabs/aws-cloudfront-extensions/blob/main/edge/nodejs/serving-based-on-device/serving-based-on-device/tests/unit/test-handler.js#L14), and function timeout should be 5 seconds, not 30 seconds. [document](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-see-limits)

template
https://github.com/awslabs/aws-cloudfront-extensions/blob/main/edge/nodejs/serving-based-on-device/template.yaml#L13

### Reproduction Steps

serving-based-on-device function associate to `CloudFrontWebDistribution`

### What did you expect to happen?

deploy successfully

### What actually happened?

get error
```
The function timeout is larger than the maximum allowed for functions that are triggered by a CloudFront event: 30 Max allowed: 5 Function: arn:aws:lambda:us-east-1:628531345753:function:demo-ServingDerv
iceBC28F36-ServingOnDeviceFunction-1LE1W6SEOWIM9:1 (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidLambdaFunctionAssociation; Request ID: 92639406-f1e6-44bc-a2c5-4955d7fc4618; Proxy: nul
l)
```

### Environment

  - **CDK CLI Version  : 1.73.0**
  - **Framework Version:**
  - **Language (Version):**

**Comment by NingLu** [comment]
Hi Rico,

The [PR](https://github.com/awslabs/aws-cloudfront-extensions/pull/113) has been merged, would you try it again?

**Comment by RicoToothless** [comment]
Can you help me to release a new version on Serverless Application Repository?
