### ISSUE TITLE
source code url is out of date

### ISSUE THREAD

**Issue by zxkane** [awslabs/aws-cloudfront-extensions#127]
For example,

https://github.com/awslabs/aws-cloudfront-extensions/blob/main/edge/nodejs/add-security-headers/add-security-headers/package.json#L6

Also this out of date url is showed in SAR.

https://ap-southeast-1.console.aws.amazon.com/lambda/home?region=ap-southeast-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:418289889111:applications/add-security-headers

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Language (Version):**

**Comment by NingLu** [comment]
@zxkane The issue has been fixed in https://github.com/awslabs/aws-cloudfront-extensions/commit/c8edd9f45961562d0044836346881ba430fe9204
