### ISSUE TITLE
how deploy cdk supported lambda@edge

### ISSUE THREAD

**Issue by zxkane** [awslabs/aws-cloudfront-extensions#128]
### The Question

I do see the deployment type of few Lambda@Edge functions are **CDK** in [link](https://github.com/awslabs/aws-cloudfront-extensions/blob/main/docs/LambdaEdge.md#security). Then clicking the CDK link(for example, [this one](https://github.com/awslabs/aws-cloudfront-extensions/tree/main/edge/nodejs/add-security-headers)), it’s a project developed by SAM.

Pls guide how to use the functions with CDK!

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Language (Version):**

**Comment by NingLu** [comment]
The link goes to a wrong page, have fixed it

As for using add-security-header in CDK, basically it contains two steps
1. Define the CF extensions in extensions.ts which has been completed, https://github.com/pahud/cdk-cloudfront-plus/blob/main/src/extensions.ts#L138
2. Use it in your CDK script, here's an example, https://github.com/pahud/cdk-cloudfront-plus/blob/main/src/demo/modify-response-header/index.ts
