### ISSUE TITLE
role name of func ‘add-security-headers’ might exceed the limitation

### ISSUE THREAD

**Issue by zxkane** [awslabs/aws-cloudfront-extensions#130]
Deploying the func ‘add-security-headers’ failed due to the length of role name exceed the limitation

> 1 validation error detected: Value 'realtime-fraud-detection-with-gnn-on-dgl-dashboardNestedStackdashboardNestedS-Resource-9H1DRR5KKLH4-edgeFunction' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: de66a180-a963-4c98-921b-52f03f110c83; Proxy: null)

### Reproduction Steps

Deploy the func with long stack name(it’s generated by nested stack).

### What did you expect to happen?

The func can be deployed successfully without error.

Per the doc of [AWS::IAM::Role](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-rolename), the role is optional. pls let the CFN creating it for need.

### What actually happened?

see above

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Language (Version):**

**Comment by NingLu** [comment]
@zxkane Nice catching~, it's been fixed in https://github.com/awslabs/aws-cloudfront-extensions/commit/8fc597154c48c1910a97e37ab0f81ee93801d3ec , feel free to reopen if it still exist
