### ISSUE TITLE
aws-cloudfront-waf template problem for ALB

### ISSUE THREAD

**Issue by kimisme9386** [awslabs/aws-cloudfront-extensions#164]
`The Scanners and Probes (G)` rule is invalid when use aws-cloudfront-waf template for application load balancer(ALB).

### Reproduction Steps

1. Specify value "REGIONAL" for waf2Scope parameter and associate Application Load Balancer
2. Enable ALB access log  and specify it in s3 bucket location with `appAccessLogBucket`
3. Make many API requests more than `errorThreshold` setting and these API requests are response 401 http status code

### What did you expect to happen?

The source ip address of these API requests will be shown in `Scanners and Probes (G)` rule.

### What actually happened?

`Scanners and Probes (G)` rule has no any ip address.

### Environment

  - **CDK CLI Version  :**  1.111.0
  - **Framework Version:** 
  - **Language (Version):**  node v14.16.1

### Other

I rebuild it from CDK stack to CDK construct in [cdk-automated-waf](https://github.com/kimisme9386/cdk-automated-waf) because CDK construct can be used by others project vary handy.

If cdk-automated-waf can merge in this repository, please let me known.

**Comment by NingLu** [comment]
@kimisme9386 it is based on CloudFront, so ALB will not be supported

If you need to deploy WAF rules for ALB, try this solution
https://aws.amazon.com/solutions/implementations/aws-waf-security-automations/?did=sl_card&trk=sl_card

**Comment by kimisme9386** [comment]
@NingLu I have looked over the source code of lambda in this project which contains ALB log type check, such as [here](https://github.com/awslabs/aws-cloudfront-extensions/blob/main/templates/aws-cloudfront-waf/source/log_parser/log-parser.py#L465). 

The aws-cloudfront-waf template has [WAFScope parameter](https://github.com/awslabs/aws-cloudfront-extensions/blob/main/templates/aws-cloudfront-waf/lib/aws-cloudfront-waf-main.ts#L61-L65) to choose CloudFront or REGIONAL(The REGIONAL support ALB、API Gateway、AppSync). I thought it supported ALB but had some bug. 

I have created PR #165  for it. 
BTW I also have built CDK Construct [cdk-automated-waf ](https://github.com/kimisme9386/cdk-automated-waf) to use it more handy than CDK Stack.

**Comment by NingLu** [comment]
The ALB related codes in lambda functions will be removed in next release, 

Thanks for contributing, but the solution is aim to deploy WAF & Shield Advanced on CloudFront only, so ALB/API gateway support is out of the solution's scope (even though it can be added in cdk script) and will not be supported in the future

WAF Automation solution is for deploying WAF rules on ALB

**Comment by kimisme9386** [comment]
> The ALB related codes in lambda functions will be removed in next release,
> 
> Thanks for contributing, but the solution is aim to deploy WAF & Shield Advanced on CloudFront only, so ALB/API gateway support is out of the solution's scope (even though it can be added in cdk script) and will not be supported in the future
> 
> WAF Automation solution is for deploying WAF rules on ALB

Ok, got it. Thanks for your reply.
