### ISSUE TITLE
Add cost estimation for solution

### ISSUE THREAD

**Issue by ensean** [awslabs/aws-cloudfront-extensions#239]
### Use Case

Let the enduser estimate the cost before deploy the solution

### Proposed Solution

Give out sample cost estimation based on different request volumes, such as 1M/day, 2M/day

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NingLu** [comment]
@ensean Cost estimation is in progress, will get back to you once it is completed

**Comment by NingLu** [comment]
The cost estimation can be found in https://awslabs.github.io/aws-cloudfront-extensions/en/cost/
