### ISSUE TITLE
Documented deployment sample does not work

### ISSUE THREAD

**Issue by adgang** [awslabs/aws-cloudfront-extensions#372]
Documentation in https://awslabs.github.io/aws-cloudfront-extensions/en/deployment/ to launch a console does not work

### Reproduction Steps
1. Go to https://awslabs.github.io/aws-cloudfront-extensions/en/deployment/
2. Click on Launch Stack
3. Fill in appropriate details and continue

### What did you expect to happen?
The stack should have allocated resources

### What actually happened?

```
Received response status [FAILED] from custom resource. Message returned: Error: Unable to import module 'custom_resource': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py) Logs: /aws/lambda/CloudFrontExtensionsConso-RepoConstructSyncExtensi-zjvIaRCZCn8u at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:1:365) at async Runtime.handler (/var/task/cfn-response.js:1:1474)
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Language (Version):** 
Nodejs14.x Python 3.9

**Comment by adgang** [comment]
Update:
When I replace the python version to python3.11 in the template json, the new file worked fine for creation of the stack. But then when I try to install extensions, or when clicking on Check Updates, the following error shows up:

```
Oops...
Unable to import module 'deployer': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py)
```

**Comment by NingLu** [comment]
It has been fixed, please try the CloudFormation template in https://www.amazonaws.cn/en/solutions/amazon-cloudfront-extensions/?nc1=h_ls

Feel free to reopen if it still not working
