### ISSUE TITLE
Access origin by geolocation

### ISSUE THREAD

**Issue by NingLu** [awslabs/aws-cloudfront-extensions#88]
Access origin by geolocation, it will generate an HTTP redirect response with a country-specific URL and return the response to the viewer, for example, if the user is in US, it will return us.example.com, if the user is in CN, it will return cn.example.com

CloudFront-Viewer-Country can be used here to identify the geolocation

Solution id: SO8118
Package name: cf-access-origin-by-geolocation

### Use Case

The user has some country-specific subdomains, such as us.example.com and tw.example.com, the user is able to generate a redirect response when a viewer requests example.com.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
I believe we have two scenarios here

1.  302 location redirect - simply redirect the client to the new location
2. modify the host header and send to the new origin. We have a blog post regarding this [here](https://aws.amazon.com/tw/blogs/networking-and-content-delivery/dynamically-route-viewer-requests-to-any-origin-using-lambdaedge/).

**Comment by NingLu** [comment]
Please refer to 
https://github.com/awslabs/aws-cloudfront-extensions/tree/main/function/js/redirect-based-on-country
